### PR TITLE
Add agent & timeout options

### PR DESCRIPTION
**Pull request by mousavian**
This will provides more options such as enabling `keep-alive` connection through `httpAgent` and setting timeout on http requests.
  
[Http interface document](https://nodejs.org/api/http.html#http_http_request_options_callback)

### CODE REVIEW

**Comment by yongfei25** [comment]
When can we get this merged? :)

**Review by obrin — APPROVED** [review]

**Comment by SomeoneWeird** [comment]
Hi! Apologies, have been on holiday and intentionally avoided Github :)

**Comment by SomeoneWeird** [comment]
@mousavian Are you able to make a PR to https://github.com/hudson-taylor/hudson-taylor.github.io/blob/master/_docs/transports-http.md and add the new options please?

**Comment by mousavian** [comment]
@SomeoneWeird oh yea sure. will do

**Comment by SomeoneWeird** [comment]
Published @ 1.0.5

**Pull request merged**
